name: Release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-
      - name: Get version number
        id: version
        run: |
          VERSION=$(cat version.txt)
          echo "VERSION=${VERSION}" >> $GITHUB_ENV
          echo "::set-output name=version::${VERSION}"
      - name: Build & push multi-platform image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile
          push: true
          tags: |
            myimage:latest
            myimage:${{ steps.version.outputs.version }}
          labels: |
            org.opencontainers.image.title=IPTV Stream Manager
            org.opencontainers.image.source=${{ github.repository }}
            org.opencontainers.image.version=${{ steps.version.outputs.version }}
      - name: Notify Discord
        if: success()
        uses: discordapp/discord-webhook-action@v1.0.1
        with:
          webhook-url: ${{ secrets.DISCORD_WEBHOOK_URL }}
          message: 'New release: ${{ steps.version.outputs.version }} deployed successfully!'
          username: 'Release Bot'
          avatar-url: 'https://example.com/avatar.png'